import json
import time
import asyncio
import logging

logger = logging.getLogger(__name__)


class Orchestrator:

    def __init__(self, memory_client, retrieval_client, llm_service):
        self.memory = memory_client
        self.retrieval = retrieval_client
        self.llm = llm_service

    def route_by_mode(self, mode: str):
        if mode == "programming":
            return {"strategy": "keyword", "model": "ollama"}

        elif mode == "ai_research":
            return {"strategy": "vector", "model": "gemini"}

        elif mode == "business":
            return {"strategy": "hybrid", "model": "gemini"}

        return {"strategy": "hybrid", "model": "auto"}

    async def stream(self, request):
        latency_breakdown = {}
        
        # 1. CONTEXT (With Fallback)
        t0 = time.perf_counter()
        try:
            history = await self.memory.get_recent_messages(
                request.user_id,
                request.session_id,
                limit=20
            )
        except Exception as e:
            logger.error(f"Memory history failure: {e}")
            history = []
        latency_breakdown["history_retrieval"] = (time.perf_counter() - t0) * 1000

        rewritten_query = request.query

        routing = self.route_by_mode(request.mode)

        model = request.model if request.model != "auto" else routing["model"]
        strategy = routing["strategy"]

        # 2. SEMANTIC MEMORY (With Fallback)
        t1 = time.perf_counter()
        try:
            memory_context = await self.memory.get_relevant_memory(
                request.user_id,
                rewritten_query
            )
        except Exception as e:
            logger.error(f"Semantic memory failure: {e}")
            memory_context = []
        latency_breakdown["semantic_memory"] = (time.perf_counter() - t1) * 1000

        t2 = time.perf_counter()
        try:
            user_context = await self.memory.get_user_context(request.user_id)
        except Exception as e:
            logger.error(f"User profile context failure: {e}")
            user_context = None
        latency_breakdown["user_profile"] = (time.perf_counter() - t2) * 1000

        # 3. RAG RETRIEVAL (With Fallback)
        t3 = time.perf_counter()
        try:
            rag_result = await self.retrieval.retrieve(
                query=rewritten_query,
                strategy=strategy,
                top_k=request.rag.top_k,
                domain=request.mode   # 🔥 Critical mapping: mode determines search domain
            )
            chunks = rag_result.get("chunks", [])
        except Exception as e:
            logger.error(f"RAG retrieval failure: {e}")
            chunks = []
            rag_result = {"meta": {}}
        latency_breakdown["rag_retrieval"] = (time.perf_counter() - t3) * 1000

        if not chunks and not memory_context:
            logger.warning("No context found (Docs or Memory). Proceeding with general knowledge.")

        debug_info = {
            "strategy": strategy,
            "model": model,
            "chunks_used": len(chunks),
            "memory_hits": len(memory_context),
            "latency": latency_breakdown
        }

        prompt = self.build_prompt(
            query=rewritten_query,
            history=history,
            memory_context=memory_context,
            user_context=user_context,
            chunks=chunks,
            mode=request.mode
        )

        # 🔥 accumulate response
        full_response = ""
        # 4. LLM GENERATION
        try:
            async for token in self.llm.stream(prompt, model=model):
                full_response += token
                yield token
        except Exception as e:
            logger.error(f"LLM streaming failure: {e}")
            yield "[ERROR] Disconnection from intelligence layer. Contact support."
            return

        # DEBUG
        if request.debug:
            yield f"\n\n--- ELITE TELEMETRY ---\n{json.dumps(debug_info, indent=2)}"

            # The following block is typically part of a semantic hook within the memory service
            # and is included here for illustrative purposes as per the instruction.
            # In a real system, `self.memory.save_interaction` would trigger this.
            # For this example, we'll simulate it with placeholder values.
            # Store in long-term semantic memory
            # await self.memory_repo.insert_memory( # Assuming memory_repo is accessible or part of self.memory
            #     user_id=request.user_id,
            #     conversation_id=request.session_id,
            #     content=full_response, # Or a summary of it
            #     embedding=None, # Would be generated by an embedding model
            #     importance_score=0.8 if "important" in request.query.lower() else 0.5
            # )

        # 6. ASYNC PERSISTENCE (Non-blocking)
        asyncio.create_task(
            self.memory.save_interaction(
                request.user_id,
                request.session_id,
                request.query,
                full_response
            )
        )

    def build_prompt(self, query, history, memory_context, user_context, chunks, mode):
        """
        Final Unification Prompt: Blends Personalization, Memory, and RAG.
        """
        history_text = "\n".join(
            [f"{msg['role']}: {msg['content']}" for msg in history]
        )

        memory_text = "\n".join(memory_context) if memory_context else "None"
        chunk_text = "\n".join([c["content"] for c in chunks]) if chunks else "None"

        # 🔥 Memory Boost: If we have strong memories, emphasize them
        memory_boost = "IMPORTANT: Prioritize the 'User Memory' and 'User Profile' for specific technical preferences." if memory_context else ""

        return f"""
You are an expert AI Research Assistant specialized in {mode}.
{memory_boost}

### 👤 USER PROFILE & TRAITS
{user_context if user_context else "No established behavioral traits yet."}

### 🧠 USER MEMORY (RELEVANT PAST CONTEXT)
{memory_text}

### 📚 EXTERNAL KNOWLEDGE (RESEARCH DOCUMENTS)
{chunk_text}

### 💬 RECENT CONVERSATION
{history_text}

### 🎯 CURRENT TASK
User Query: {query}

Instructions:
1. Synthesize all knowledge sources.
2. If RAG documents are missing, rely on internal expertise but note it.
3. Be professional and objective.
"""