import json


class Orchestrator:

    def __init__(self, memory_client, retrieval_client, llm_service):
        self.memory = memory_client
        self.retrieval = retrieval_client
        self.llm = llm_service

    def route_by_mode(self, mode: str):
        if mode == "programming":
            return {"strategy": "keyword", "model": "ollama"}

        elif mode == "ai_research":
            return {"strategy": "vector", "model": "gemini"}

        elif mode == "business":
            return {"strategy": "hybrid", "model": "gemini"}

        return {"strategy": "hybrid", "model": "auto"}

    async def stream(self, request):

        # 1. CONTEXT
        history = await self.memory.get_recent_messages(
            request.user_id,
            request.session_id,
            limit=20
        )

        rewritten_query = request.query

        routing = self.route_by_mode(request.mode)

        model = request.model if request.model != "auto" else routing["model"]
        strategy = routing["strategy"]

        # 2. SEMANTIC MEMORY (NEW)
        memory_context = await self.memory.get_relevant_memory(
            request.user_id,
            rewritten_query
        )

        user_context = await self.memory.get_user_context(request.user_id)

        rag_result = await self.retrieval.retrieve(
            query=rewritten_query,
            strategy=strategy,
            top_k=request.rag.top_k,
            domain=request.mode   # 🔥 Critical mapping: mode determines search domain
        )

        chunks = rag_result.get("chunks", [])

        if not chunks:
            yield "No relevant documents found."
            return

        debug_info = {
            "strategy": strategy,
            "model": model,
            "chunks_used": len(chunks),
            "memory_hits": len(memory_context),
            "latency": rag_result.get("meta", {})
        }

        prompt = self.build_prompt(
            query=rewritten_query,
            history=history,
            memory_context=memory_context,
            user_context=user_context,
            chunks=chunks,
            mode=request.mode
        )

        # 🔥 accumulate response
        full_response = ""

        async for token in self.llm.stream(prompt, model=model):
            full_response += token
            yield token

        # DEBUG
        if request.debug:
            yield "\n\n--- DEBUG INFO ---\n"
            yield json.dumps(debug_info, indent=2)

            # The following block is typically part of a semantic hook within the memory service
            # and is included here for illustrative purposes as per the instruction.
            # In a real system, `self.memory.save_interaction` would trigger this.
            # For this example, we'll simulate it with placeholder values.
            # Store in long-term semantic memory
            # await self.memory_repo.insert_memory( # Assuming memory_repo is accessible or part of self.memory
            #     user_id=request.user_id,
            #     conversation_id=request.session_id,
            #     content=full_response, # Or a summary of it
            #     embedding=None, # Would be generated by an embedding model
            #     importance_score=0.8 if "important" in request.query.lower() else 0.5
            # )

        # 🔥 SAVE RESPONSE (Triggers Semantic Hook)
        await self.memory.save_interaction(
            request.user_id,
            request.session_id,
            request.query,
            full_response
        )

    def build_prompt(self, query, history, memory_context, user_context, chunks, mode):
        """
        Final Unification Prompt: Blends Personalization, Memory, and RAG.
        """
        history_text = "\n".join(
            [f"{msg['role']}: {msg['content']}" for msg in history]
        )

        memory_text = "\n".join(memory_context)
        chunk_text = "\n".join([c["content"] for c in chunks])

        # 🔥 Memory Boost: If we have strong memories, emphasize them
        memory_boost = "IMPORTANT: Prioritize the 'User Memory' and 'User Profile' below as they contain specific user preferences and past corrections." if memory_context else ""

        return f"""
You are an expert AI Research Assistant specialized in {mode}.
{memory_boost}

### 👤 USER PROFILE & TRAITS
{user_context if user_context else "No established behavioral traits yet."}

### 🧠 USER MEMORY (RELEVANT PAST CONTEXT)
{memory_text if memory_text else "No directly relevant past interactions found."}

### 📚 EXTERNAL KNOWLEDGE (RESEARCH DOCUMENTS)
{chunk_text}

### 💬 RECENT CONVERSATION
{history_text}

### 🎯 CURRENT TASK
User Query: {query}

Instructions:
1. Use 'EXTERNAL KNOWLEDGE' for general technical facts.
2. Use 'USER MEMORY' and 'USER PROFILE' to adapt the tone, detail level, and specific preferences (e.g., tool choices).
3. If the user asks about something you've discussed before (see Memory), acknowledge it.
4. If information is missing from all sources, provide a helpful synthesis based on your internal knowledge but mark it as 'General AI Knowledge'.
"""